type CountryName =
  | "Andorra"
  | "United Arab Emirates"
  | "Afghanistan"
  | "Antigua and Barbuda"
  | "Anguilla"
  | "Albania"
  | "Armenia"
  | "Angola"
  | "Antarctica"
  | "Argentina"
  | "American Samoa"
  | "Austria"
  | "Australia"
  | "Aruba"
  | "Åland Islands"
  | "Azerbaijan"
  | "Bosnia and Herzegovina"
  | "Barbados"
  | "Bangladesh"
  | "Belgium"
  | "Burkina Faso"
  | "Bulgaria"
  | "Bahrain"
  | "Burundi"
  | "Benin"
  | "Saint Barthélemy"
  | "Bermuda"
  | "Brunei Darussalam"
  | "Bolivia, Plurinational State of"
  | "Bonaire, Sint Eustatius and Saba"
  | "Brazil"
  | "Bahamas"
  | "Bhutan"
  | "Bouvet Island"
  | "Botswana"
  | "Belarus"
  | "Belize"
  | "Canada"
  | "Cocos (Keeling) Islands"
  | "Congo, Democratic Republic of the"
  | "Central African Republic"
  | "Congo"
  | "Switzerland"
  | "Côte d'Ivoire"
  | "Cook Islands"
  | "Chile"
  | "Cameroon"
  | "China"
  | "Colombia"
  | "Costa Rica"
  | "Cuba"
  | "Cabo Verde"
  | "Curaçao"
  | "Christmas Island"
  | "Cyprus"
  | "Czechia"
  | "Germany"
  | "Djibouti"
  | "Denmark"
  | "Dominica"
  | "Dominican Republic"
  | "Algeria"
  | "Ecuador"
  | "Estonia"
  | "Egypt"
  | "Western Sahara"
  | "Eritrea"
  | "Spain"
  | "Ethiopia"
  | "Finland"
  | "Fiji"
  | "Falkland Islands (Malvinas)"
  | "Micronesia, Federated States of"
  | "Faroe Islands"
  | "France"
  | "Gabon"
  | "United Kingdom of Great Britain and Northern Ireland"
  | "Grenada"
  | "Georgia"
  | "French Guiana"
  | "Guernsey"
  | "Ghana"
  | "Gibraltar"
  | "Greenland"
  | "Gambia"
  | "Guinea"
  | "Guadeloupe"
  | "Equatorial Guinea"
  | "Greece"
  | "South Georgia and the South Sandwich Islands"
  | "Guatemala"
  | "Guam"
  | "Guinea-Bissau"
  | "Guyana"
  | "Hong Kong"
  | "Heard Island and McDonald Islands"
  | "Honduras"
  | "Croatia"
  | "Haiti"
  | "Hungary"
  | "Indonesia"
  | "Ireland"
  | "Israel"
  | "Isle of Man"
  | "India"
  | "British Indian Ocean Territory"
  | "Iraq"
  | "Iran, Islamic Republic of"
  | "Iceland"
  | "Italy"
  | "Jersey"
  | "Jamaica"
  | "Jordan"
  | "Japan"
  | "Kenya"
  | "Kyrgyzstan"
  | "Cambodia"
  | "Kiribati"
  | "Comoros"
  | "Saint Kitts and Nevis"
  | "Korea, Democratic People's Republic of"
  | "Korea, Republic of"
  | "Kuwait"
  | "Cayman Islands"
  | "Kazakhstan"
  | "Lao People's Democratic Republic"
  | "Lebanon"
  | "Saint Lucia"
  | "Liechtenstein"
  | "Sri Lanka"
  | "Liberia"
  | "Lesotho"
  | "Lithuania"
  | "Luxembourg"
  | "Latvia"
  | "Libya"
  | "Morocco"
  | "Monaco"
  | "Moldova, Republic of"
  | "Montenegro"
  | "Saint Martin, (French part)"
  | "Madagascar"
  | "Marshall Islands"
  | "North Macedonia"
  | "Mali"
  | "Myanmar"
  | "Mongolia"
  | "Macao"
  | "Northern Mariana Islands"
  | "Martinique"
  | "Mauritania"
  | "Montserrat"
  | "Malta"
  | "Mauritius"
  | "Maldives"
  | "Malawi"
  | "Mexico"
  | "Malaysia"
  | "Mozambique"
  | "Namibia"
  | "New Caledonia"
  | "Niger"
  | "Norfolk Island"
  | "Nigeria"
  | "Nicaragua"
  | "Netherlands"
  | "Norway"
  | "Nepal"
  | "Nauru"
  | "Niue"
  | "New Zealand"
  | "Oman"
  | "Panama"
  | "Peru"
  | "French Polynesia"
  | "Papua New Guinea"
  | "Philippines"
  | "Pakistan"
  | "Poland"
  | "Saint Pierre and Miquelon"
  | "Pitcairn"
  | "Puerto Rico"
  | "Palestine, State of"
  | "Portugal"
  | "Palau"
  | "Paraguay"
  | "Qatar"
  | "Réunion"
  | "Romania"
  | "Serbia"
  | "Russian Federation"
  | "Rwanda"
  | "Saudi Arabia"
  | "Solomon Islands"
  | "Seychelles"
  | "Sudan"
  | "Sweden"
  | "Singapore"
  | "Saint Helena, Ascension and Tristan da Cunha"
  | "Slovenia"
  | "Svalbard and Jan Mayen"
  | "Slovakia"
  | "Sierra Leone"
  | "San Marino"
  | "Senegal"
  | "Somalia"
  | "Suriname"
  | "South Sudan"
  | "Sao Tome and Principe"
  | "El Salvador"
  | "Sint Maarten, (Dutch part)"
  | "Syrian Arab Republic"
  | "Eswatini"
  | "Turks and Caicos Islands"
  | "Chad"
  | "French Southern Territories"
  | "Togo"
  | "Thailand"
  | "Tajikistan"
  | "Tokelau"
  | "Timor-Leste"
  | "Turkmenistan"
  | "Tunisia"
  | "Tonga"
  | "Türkiye"
  | "Trinidad and Tobago"
  | "Tuvalu"
  | "Taiwan, Province of China"
  | "Tanzania, United Republic of"
  | "Ukraine"
  | "Uganda"
  | "United States Minor Outlying Islands"
  | "United States of America"
  | "Uruguay"
  | "Uzbekistan"
  | "Holy See"
  | "Saint Vincent and the Grenadines"
  | "Venezuela, Bolivarian Republic of"
  | "Virgin Islands, British"
  | "Virgin Islands, U.S."
  | "Viet Nam"
  | "Vanuatu"
  | "Wallis and Futuna"
  | "Samoa"
  | "Yemen"
  | "Mayotte"
  | "South Africa"
  | "Zambia"
  | "Zimbabwe";
type CountryFlag =
 | ":flag_AD:"
  | ":flag_AE:"
  | ":flag_AF:"
  | ":flag_AG:"
  | ":flag_AI:"
  | ":flag_AL:"
  | ":flag_AM:"
  | ":flag_AO:"
  | ":flag_AQ:"
  | ":flag_AR:"
  | ":flag_AS:"
  | ":flag_AT:"
  | ":flag_AU:"
  | ":flag_AW:"
  | ":flag_AX:"
  | ":flag_AZ:"
  | ":flag_BA:"
  | ":flag_BB:"
  | ":flag_BD:"
  | ":flag_BE:"
  | ":flag_BF:"
  | ":flag_BG:"
  | ":flag_BH:"
  | ":flag_BI:"
  | ":flag_BJ:"
  | ":flag_BL:"
  | ":flag_BM:"
  | ":flag_BN:"
  | ":flag_BO:"
  | ":flag_BQ:"
  | ":flag_BR:"
  | ":flag_BS:"
  | ":flag_BT:"
  | ":flag_BV:"
  | ":flag_BW:"
  | ":flag_BY:"
  | ":flag_BZ:"
  | ":flag_CA:"
  | ":flag_CC:"
  | ":flag_CD:"
  | ":flag_CF:"
  | ":flag_CG:"
  | ":flag_CH:"
  | ":flag_CI:"
  | ":flag_CK:"
  | ":flag_CL:"
  | ":flag_CM:"
  | ":flag_CN:"
  | ":flag_CO:"
  | ":flag_CR:"
  | ":flag_CU:"
  | ":flag_CV:"
  | ":flag_CW:"
  | ":flag_CX:"
  | ":flag_CY:"
  | ":flag_CZ:"
  | ":flag_DE:"
  | ":flag_DJ:"
  | ":flag_DK:"
  | ":flag_DM:"
  | ":flag_DO:"
  | ":flag_DZ:"
  | ":flag_EC:"
  | ":flag_EE:"
  | ":flag_EG:"
  | ":flag_EH:"
  | ":flag_ER:"
  | ":flag_ES:"
  | ":flag_ET:"
  | ":flag_FI:"
  | ":flag_FJ:"
  | ":flag_FK:"
  | ":flag_FM:"
  | ":flag_FO:"
  | ":flag_FR:"
  | ":flag_GA:"
  | ":flag_GB:"
  | ":flag_GD:"
  | ":flag_GE:"
  | ":flag_GF:"
  | ":flag_GG:"
  | ":flag_GH:"
  | ":flag_GI:"
  | ":flag_GL:"
  | ":flag_GM:"
  | ":flag_GN:"
  | ":flag_GP:"
  | ":flag_GQ:"
  | ":flag_GR:"
  | ":flag_GS:"
  | ":flag_GT:"
  | ":flag_GU:"
  | ":flag_GW:"
  | ":flag_GY:"
  | ":flag_HK:"
  | ":flag_HM:"
  | ":flag_HN:"
  | ":flag_HR:"
  | ":flag_HT:"
  | ":flag_HU:"
  | ":flag_ID:"
  | ":flag_IE:"
  | ":flag_IL:"
  | ":flag_IM:"
  | ":flag_IN:"
  | ":flag_IO:"
  | ":flag_IQ:"
  | ":flag_IR:"
  | ":flag_IS:"
  | ":flag_IT:"
  | ":flag_JE:"
  | ":flag_JM:"
  | ":flag_JO:"
  | ":flag_JP:"
  | ":flag_KE:"
  | ":flag_KG:"
  | ":flag_KH:"
  | ":flag_KI:"
  | ":flag_KM:"
  | ":flag_KN:"
  | ":flag_KP:"
  | ":flag_KR:"
  | ":flag_KW:"
  | ":flag_KY:"
  | ":flag_KZ:"
  | ":flag_LA:"
  | ":flag_LB:"
  | ":flag_LC:"
  | ":flag_LI:"
  | ":flag_LK:"
  | ":flag_LR:"
  | ":flag_LS:"
  | ":flag_LT:"
  | ":flag_LU:"
  | ":flag_LV:"
  | ":flag_LY:"
  | ":flag_MA:"
  | ":flag_MC:"
  | ":flag_MD:"
  | ":flag_ME:"
  | ":flag_MF:"
  | ":flag_MG:"
  | ":flag_MH:"
  | ":flag_MK:"
  | ":flag_ML:"
  | ":flag_MM:"
  | ":flag_MN:"
  | ":flag_MO:"
  | ":flag_MP:"
  | ":flag_MQ:"
  | ":flag_MR:"
  | ":flag_MS:"
  | ":flag_MT:"
  | ":flag_MU:"
  | ":flag_MV:"
  | ":flag_MW:"
  | ":flag_MX:"
  | ":flag_MY:"
  | ":flag_MZ:"
  | ":flag_NA:"
  | ":flag_NC:"
  | ":flag_NE:"
  | ":flag_NF:"
  | ":flag_NG:"
  | ":flag_NI:"
  | ":flag_NL:"
  | ":flag_NO:"
  | ":flag_NP:"
  | ":flag_NR:"
  | ":flag_NU:"
  | ":flag_NZ:"
  | ":flag_OM:"
  | ":flag_PA:"
  | ":flag_PE:"
  | ":flag_PF:"
  | ":flag_PG:"
  | ":flag_PH:"
  | ":flag_PK:"
  | ":flag_PL:"
  | ":flag_PM:"
  | ":flag_PN:"
  | ":flag_PR:"
  | ":flag_PS:"
  | ":flag_PT:"
  | ":flag_PW:"
  | ":flag_PY:"
  | ":flag_QA:"
  | ":flag_RE:"
  | ":flag_RO:"
  | ":flag_RS:"
  | ":flag_RU:"
  | ":flag_RW:"
  | ":flag_SA:"
  | ":flag_SB:"
  | ":flag_SC:"
  | ":flag_SD:"
  | ":flag_SE:"
  | ":flag_SG:"
  | ":flag_SH:"
  | ":flag_SI:"
  | ":flag_SJ:"
  | ":flag_SK:"
  | ":flag_SL:"
  | ":flag_SM:"
  | ":flag_SN:"
  | ":flag_SO:"
  | ":flag_SR:"
  | ":flag_SS:"
  | ":flag_ST:"
  | ":flag_SV:"
  | ":flag_SX:"
  | ":flag_SY:"
  | ":flag_SZ:"
  | ":flag_TC:"
  | ":flag_TD:"
  | ":flag_TF:"
  | ":flag_TG:"
  | ":flag_TH:"
  | ":flag_TJ:"
  | ":flag_TK:"
  | ":flag_TL:"
  | ":flag_TM:"
  | ":flag_TN:"
  | ":flag_TO:"
  | ":flag_TR:"
  | ":flag_TT:"
  | ":flag_TV:"
  | ":flag_TW:"
  | ":flag_TZ:"
  | ":flag_UA:"
  | ":flag_UG:"
  | ":flag_UM:"
  | ":flag_US:"
  | ":flag_UY:"
  | ":flag_UZ:"
  | ":flag_VA:"
  | ":flag_VC:"
  | ":flag_VE:"
  | ":flag_VG:"
  | ":flag_VI:"
  | ":flag_VN:"
  | ":flag_VU:"
  | ":flag_WF:"
  | ":flag_WS:"
  | ":flag_YE:"
  | ":flag_YT:"
  | ":flag_ZA:"
  | ":flag_ZM:"
  | ":flag_ZW:";

 export type { CountryName, CountryFlag };